name: "Build"
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Build"
        uses: docker://josejulio/hypha-builder:latest
        env:
          CODE: "/github/workspace/"
