name: "Test"
on: [push, pull_request]
jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
        with:
          submodules: recursive
      - name: "Build"
        uses: docker://josejulio/hypha-builder:release_1.7.x
        with:
          args: " -j2 VERBOSE=1 "
        env:
          CODE: "/github/workspace/"
          PATCH_WASM_LD: "1"
      - name: "Test"
        uses: docker://josejulio/hypha-test:release_2.0.x
        env:
          CODE: "/github/workspace/dao-go"
          INTERACTIVE_MODE: "false"
        with:
          args: "-v -timeout 6h"
